backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

# Collections define the structure for the different content types on your static site.
# Check out https://www.netlifycms.org/docs/add-to-your-site/#collections
collections:
    - name: "blog"
      label: "Blog"
      folder: "src/pages/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "blog-post",
          }
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Description", name: "description", widget: "text" }
        - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
        - { label: "Featured Image", name: "featuredimage", widget: image }
        - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
